### ISSUE TITLE
打出来的字按回车发送却没发出去

### ISSUE THREAD

**Issue by 20171213** [coralfox/Destiny-2-CN-Chat#1]
这算是bug吗

**Comment by 20171213** [comment]
具体表现为，在工具的文本框输入文字后按回车时游戏的聊天窗口会闪一秒（可以看到游戏聊天的输入框有显示刚才输入的文字），但是文字没有发送出去，相当于什么都没有发生，打10句话只能发出一两句

**Comment by coralfox** [comment]
[Destiny 2 CN Chat.zip](https://github.com/coralfox/Destiny-2-CN-Chat/files/4441497/Destiny.2.CN.Chat.zip)

看了下脚本.可能是因为延时的问题.我设置的发送延时为50毫秒(MS),在网速不是很稳定的情况下,也许就会出现此类问题...

但是因为我已经退坑了....所以没法测试了,这个就要你自己看下了

**Comment by 20171213** [comment]
> 
> [Destiny 2 CN Chat.zip](https://github.com/coralfox/Destiny-2-CN-Chat/files/4441497/Destiny.2.CN.Chat.zip)
> 
> 看了下脚本.可能是因为延时的问题.我设置的发送延时为50毫秒(MS),在网速不是很稳定的情况下,也许就会出现此类问题...
> 
> 但是因为我已经退坑了....所以没法测试了,这个就要你自己看下了
> 

好吧，也只能期望无主3官方支持中文聊天了，

**Comment by coralfox** [comment]
囧..你说的是无主3...这个是我另外一个项目....命运2的..无主3我已经更新到3.0了..应该解决你的问题了

**Comment by 20171213** [comment]
> 囧..你说的是无主3...这个是我另外一个项目....命运2的..无主3我已经更新到3.0了..应该解决你的问题了
> 

emmmm我是点任务栏图标的帮助进来的😂

**Comment by coralfox** [comment]
https://github.com/coralfox/Borderlands3-Helper/files/4425869/Borderlands3.Helper.zip   这个应该能帮你,无主之地的.哈哈哈
